#! /bin/sh

##########################
#      BSPWM CONFIG      #
##########################

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null || sxhkd &

## Workspaces
bspc monitor HDMI-0 -d ' ' ' ' ' ' ' ' ' ' ' ' ' '
bspc monitor HDMI-1 -d ' ' ' ' ' ' ' ' ' ' ' '

## bspwm options
bspc config border_width         0
bspc config window_gap           9
bspc config top_padding          0

bspc config active_border_color  "#1E1E2E"
bspc config normal_border_color  "#1E1E2E"
bspc config focused_border_color "#B77EE0"

bspc config focus_follows_pointer true
bspc config split_ratio           0.50
bspc config borderless_tiled      true
bspc config gapless_tiled         true
bspc config single_tiled          false

# No border padding in monocle
# for side in right bottom left; do bspc config ${side}_monocle_padding -8; done
# bspc config top_monocle_padding   -9

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules
# Terminal
bspc rule -a Alacritty desktop=^7 state=pseudo_tiled follow=on focus=on rectangle=900x700+0+0
# Browser
bspc rule -a firefox desktop=^2 state=tiled follow=on focus=on 
bspc rule -a Brave-browser desktop=^2 state=tiled follow=on focus=on 
bspc rule -a "Tor Browser" desktop=^8 state=tiled follow=on focus=on
# Music
bspc rule -a Spotify desktop=^4 state=tiled follow=off focus=off
# Media
bspc rule -a chatterino desktop=^11 state=floating follow=on focus=on
bspc rule -a mpv desktop=^11 state=tiled follow=on focus=on 
# File management
bspc rule -a Pcmanfm desktop=^9 state=floating follow=on focus=on center=true border=off rectangle=1100x800+0+0 
bspc rule -a Gimp desktop=^9 state=tiled follow=on focus=on
# Code editor
bspc rule -a VSCodium desktop=^10 state=tiled follow=on focus=on
bspc rule -a obsidian desktop=^10 state=tiled follow=on focus=on
# Games
bspc rule -a Steam desktop=^12 state=floating follow=on focus=on border=off center=true rectangle=1100x800+0+0
bspc rule -a airshipper desktop=^12 state=floating follow=on focus=on center=true rectangle=1100x800+0+0
bspc rule -a steam_app_1313140 desktop=^12 state=fullscreen follow=off focus=off
# Communication
bspc rule -a discord desktop=^3 state=tiled follow=on focus=off
bspc rule -a "Microsoft Teams - Preview" desktop=^3 state=tiled follow=on focus=on
# Settings
bspc rule -a Nitrogen desktop=^13 state=floating follow=on focus=on center=true border=off rectangle=1100x800+0+0
bspc rule -a Lxappearance desktop=^13 state=floating follow=on focus=on center=true border=off rectangle=1100x800+0+0
bspc rule -a Pavucontrol desktop=^13 state=floating follow=on focus=on center=true border=off rectangle=900x600+0+0 
bspc rule -a via-nativia desktop=^13 state=floating follow=on focus=on center=true rectangle=1300x800+0+0

## Autorun
bash ~/.config/polybar/scripts/launch.sh &

